---
- hosts: all
  become: yes
  tasks:
  - name: in task one install trees
    apt:
      name: tree
      state: present

  - name: in task two install git
    apt:
      name: git
      state: present
  
